import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto pt-6">
      <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-8">Terms of Service</h1>

      <div className="prose prose-slate dark:prose-invert max-w-none space-y-6 text-sm leading-relaxed text-slate-700 dark:text-slate-300">
        <p className="text-slate-500 dark:text-slate-400">Last updated: 8 March 2026</p>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mt-8 mb-3">1. Service overview</h2>
          <p>
            LaunchKit (&quot;we,&quot; &quot;us,&quot; &quot;the Service&quot;) is an AI-powered marketing plan generator.
            You provide a product URL and answer a short questionnaire; we generate a marketing brief and
            copy package delivered as a downloadable PDF.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mt-8 mb-3">2. Pricing and payment</h2>
          <p>
            Plans are available as one-time purchases at the prices displayed on the website at the time of
            checkout. All payments are processed securely via Stripe. Prices are in GBP and inclusive of VAT
            where applicable.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mt-8 mb-3">3. Delivery</h2>
          <p>
            Your PDF is generated automatically after payment and is typically ready within 1-5 minutes.
            Download links are valid for 30 days and up to 10 downloads. If generation fails, we will
            issue a full refund within 5 working days.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mt-8 mb-3">4. Refund policy</h2>
          <p>
            If we fail to deliver your plan due to a technical error, you are entitled to a full refund.
            Because plans are generated instantly using AI, we cannot offer refunds for dissatisfaction
            with the content itself. If you believe the output is fundamentally unusable, please contact
            us and we will work with you to resolve the issue.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mt-8 mb-3">5. Intellectual property</h2>
          <p>
            You own all rights to the generated content. We retain no ownership over your marketing plans,
            copy drafts, or any other output. You are free to use, modify, and distribute the content
            as you see fit.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mt-8 mb-3">6. AI-generated content</h2>
          <p>
            All text content is generated by artificial intelligence (Google Gemini). While we strive for
            accuracy and quality, AI-generated content may contain errors, inaccuracies, or suggestions
            that are not suitable for your specific situation. You are responsible for reviewing and
            adapting all content before publishing.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mt-8 mb-3">7. Data handling</h2>
          <p>
            We collect only the data necessary to generate and deliver your plan: your product URL, email
            address, and questionnaire answers. See our <a href="/privacy" className="text-indigo-600 hover:text-indigo-500 dark:text-indigo-400 underline">Privacy Policy</a> for full details.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mt-8 mb-3">8. Limitation of liability</h2>
          <p>
            The Service is provided &quot;as is.&quot; We are not liable for any indirect, incidental, or
            consequential damages arising from use of the generated content. Our total liability is
            limited to the amount you paid for the specific plan in question.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mt-8 mb-3">9. Changes to terms</h2>
          <p>
            We may update these terms from time to time. Material changes will be noted by updating the
            date at the top of this page.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mt-8 mb-3">10. Contact</h2>
          <p>
            For questions, support, or refund requests, email us at{' '}
            <a href="mailto:moltychief@agentmail.to" className="text-indigo-600 hover:text-indigo-500 dark:text-indigo-400 underline">
              moltychief@agentmail.to
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}
